### ISSUE TITLE
v0.8 - "analysis" json section is not populated

### ISSUE THREAD

**Issue by drevicko** [gsi-upm/senpy#14]
The "analysis" section contains only the name of the plugin, none of it's variables.

**Comment by balkian** [comment]
We had complains about the verbosity of the output. All the parameters are static, so it doesn't make sense to include it in *every* request, especially when we're analysing a stream of tweets.

OTOH, the name is actually a URI, so it can be used to get all the necessary info. e.g. http://senpy.cluster.gsi.dit.upm.es/api/plugins/sentiText/ (This isn't a great example, because it is not the latest version, but you get the idea).

**Comment by drevicko** [comment]
ok, makes sense, though it would be nice to be able to provide even static parameter settings if we wish, and the old system allowed for removing class variables by making them private to reduce verbosity..

also, what about the extra_params? Currently I don't see them appearing in the output, and those pretty much need to be there somewhere.

**Comment by balkian** [comment]
The old system should still be in place: private variables are not exported. If it isn't working, it is a bug.
As for the `extra_params` variable, they're there in the plugin description. e.g. http://latest.senpy.cluster.gsi.dit.upm.es/api/plugins/sentiment140 shows:

```
{
    "@context": "http://latest.senpy.cluster.gsi.dit.upm.es/api/contexts/Sentiment140Plugin.jsonld",
    "@id": "plugins/sentiment140_0.2",
    "@type": "sentimentPlugin",
    "author": "@balkian",
    "description": "Connects to the sentiment140 free API: http://sentiment140.com",
    "extra_params": {
        "language": {
            "@id": "lang_sentiment140",
            "aliases": [
                "language",
                "l"
            ],
            "options": [
                "es",
                "en",
                "auto"
            ],
            "required": false
        }
    },
    "is_activated": true,
    "maxPolarityValue": 1.0,
    "minPolarityValue": 0.0,
    "module": "sentiment140",
    "name": "sentiment140",
    "requirements": { },
    "url": "https://github.com/gsi-upm/senpy-plugins-community",
    "version": "0.2"
}
```

**Comment by drevicko** [comment]
Ok, but what about the values associated with a particular analysis of a piece of data?
eg: if I analyse the default text with language set to 'es', it doesn't recognise the emotions (not surprisingly). The returned json ought to let me know that it thought the text was spanish..

**Comment by drevicko** [comment]
Might also be a good idea to include the link to the plugin description in the returned json for each analysis result to make it easier to know where to look?

**Comment by balkian** [comment]
If you want to get the parameters as well:
```
http://latest.senpy.cluster.gsi.dit.upm.es/api/?&i=hello&with_parameters=1
```
For completeness, it should probably be the default, but I'll keep it like that for now. You probably missed that option because it wasn't included in API_PARAMETERS :)

The strings in the `analysis` part are already ids, so they are basically links, too. As proof, see: http://latest.senpy.cluster.gsi.dit.upm.es/api/?&i=hello&with_parameters=1

```
    {
        "@id": "_:Results_1488468637.2270875",
        "@type": [
            "http://latest.senpy.cluster.gsi.dit.upm.es/ns/results"
        ],
        "http://latest.senpy.cluster.gsi.dit.upm.es/ns/AnalysisInvolved": [
            {
                "@id": "http://latest.senpy.cluster.gsi.dit.upm.es/api/plugins/rand_0.1"
            }
        ]
```

**Comment by drevicko** [comment]
ok, the `with_parameters=1` option works, though I agree that it should be the default.
I tried the i=hello link above, and the only text that comes up as a  link is the context, but that's ok.

Perhaps this ought to be in the docs, as it's fairly important for actual applications.
