### ISSUE TITLE
0.8.x - Ekman2VAD plugin always present

### ISSUE THREAD

**Issue by drevicko** [gsi-upm/senpy#15]
and it generates an exception if you try to run it, but I guess that's ok (:

**Comment by balkian** [comment]
You get the error because the internal *plugin selection* mechanism is not discriminating between analysis and conversion plugins **yet**.

We should probably add a way to disable it. I changed the way `--default-plugins` works so the conversion is integrated by default, even if you don't want the other built-in plugins (e.g. sentiment140).

Thing is, I wanted to try this idea first before rewriting everything.

**Comment by drevicko** [comment]
I thought it would be something like that. 

It's easy enough to tell a conversion plugin from an analysis plugin, no? Can you not just filter them out when eg the web page front end asks for a list of plugins? At least for the web front end - having conversion plugins in the list isn't so good for a demo page..

**Comment by drevicko** [comment]
@balkian  I wonder if you could commit a version without the conversion plugins added, as currently it doesn't work from the web interface. It comes up as the default plugin too, which is confusing for people visiting a running instance.

I'll be running a demo in a week and would love it if I didn't have to explain the presence of a mysterious plugin (:

**Comment by balkian** [comment]
There's a commit with that already: https://github.com/gsi-upm/senpy/tree/12-conversion-plugins-in-playground

It'll be merged into 0.8.5 either today or tomorrow. It might include an option to do without the big GSI logo, too.
