### ISSUE TITLE
plugins that don't like activation in a thread...

### ISSUE THREAD

**Issue by drevicko** [gsi-upm/senpy#19]
we have a plugin that uses theano, which refuses to import into a thread (it's a gevent thing).

I see that senpy has a mechanism for loading plugins [synchronously](https://github.com/gsi-upm/senpy/blob/cbeb3adbdb74c9b3ed12dbbca67957f2d1fbe71a/senpy/extensions.py#L256), but there doesn't seem to be a way to use it at the moment, as the only place `activate_all()` is called is in `__main__.py` and `cli.py` where sync is left to it's default False value or set to False.

We can change that to get things working in our case, but is there a way to force a plugin to load synchronously already implemented that I didn't find?

**Comment by drevicko** [comment]
ps: as a workaround, we're using `activate_all(sync-True)` in `__main__.py`

**Comment by balkian** [comment]
Yeah, you can force your plugin to be loaded synchronously: https://github.com/gsi-upm/senpy/blob/master/senpy/extensions.py#L256
Simply add this property to your .senpy file:

```yaml
async: false 
```

We are aware of this issue, but it isn't a priority right now because most servers only have one or two plugins.
We'll probably add an `async` flag to the command line too.

**Comment by drevicko** [comment]
changed name of this issue : we need to add this to the docs..
